version: "3.8"

services:
  web:
    container_name: dev-rexone-web
    build:
      context: .
      dockerfile: ${VITE_REACT_APP_DOCKERFILE}
    env_file:
      - .env
    ports:
      - ${VITE_REACT_APP_PORT_MAP}
    volumes:
      - .:/web
      - /web/node_modules
