// tailwind.config.js
import { colors, font, radius, shadows, dropShadows, keyframes, animations } from './src/design/elements';
import daisyui from 'daisyui';
import plugin from 'tailwindcss/plugin';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [
    daisyui,
    plugin(({ addBase }) => {
      addBase({
        ':root': {
          '--font-primary': font.fontFamily.primary,
          '--font-display': font.fontFamily.display,
          '--font-handwritten': font.fontFamily.handwritten,
          '--font-mono': font.fontFamily.mono,
        },
        ':root, [data-theme="day"]': {
          '--color-primary': colors.day.primary,
          '--color-primary-rgb': colors.day.primaryRgb,
          '--color-primary-light': colors.day.primaryLight,
          '--color-primary-dark': colors.day.primaryDark,
          '--color-glow-white': colors.day.glowWhite,
          '--color-glow-outer': colors.day.glowOuter,
          '--color-glow-outer-rgb': colors.day.glowOuterRgb,
          '--color-primary-content': colors.text.night.primary,
          '--color-secondary': colors.secondary,
          '--color-secondary-content': colors.text.night.primary,
          '--color-accent': colors.accent,
          '--color-accent-content': colors.text.night.primary,
          '--color-base-100': colors.day.background,
          '--color-base-200': colors.day.surface,
          '--color-base-300': colors.day.card,
          '--color-base-content': colors.text.day.primary,
          '--color-base-content-rgb': colors.text.day.primaryRgb,
          '--color-neutral': colors.day.card,
          '--color-neutral-content': colors.text.day.primary,
          '--color-border': colors.day.border,
          '--color-divider': colors.day.divider,
          '--color-info': colors.semantic.info,
          '--color-info-content': colors.text.night.primary,
          '--color-success': colors.semantic.success,
          '--color-success-content': colors.text.night.primary,
          '--color-warning': colors.semantic.warning,
          '--color-warning-content': colors.text.night.primary,
          '--color-error': colors.semantic.error,
          '--color-error-content': colors.text.night.primary,
        },
        '[data-theme="night"]': {
          '--color-primary': colors.night.primary,
          '--color-primary-rgb': colors.night.primaryRgb,
          '--color-primary-light': colors.night.primaryLight,
          '--color-primary-dark': colors.night.primaryDark,
          '--color-glow-white': colors.night.glowWhite,
          '--color-glow-outer': colors.night.glowOuter,
          '--color-glow-outer-rgb': colors.night.glowOuterRgb,
          '--color-primary-content': colors.text.night.primary,
          '--color-secondary': colors.night.primaryLight,
          '--color-secondary-content': colors.text.night.primary,
          '--color-accent': colors.night.primary,
          '--color-accent-content': colors.text.night.primary,
          '--color-base-100': colors.night.background,
          '--color-base-200': colors.night.surface,
          '--color-base-300': colors.night.card,
          '--color-base-content': colors.text.night.primary,
          '--color-base-content-rgb': colors.text.night.primaryRgb,
          '--color-neutral': colors.night.card,
          '--color-neutral-content': colors.text.night.primary,
          '--color-border': colors.night.border,
          '--color-divider': colors.night.divider,
          '--color-info': colors.semantic.info,
          '--color-info-content': colors.text.night.primary,
          '--color-success': colors.semantic.success,
          '--color-success-content': colors.text.night.primary,
          '--color-warning': colors.semantic.warning,
          '--color-warning-content': colors.text.night.primary,
          '--color-error': colors.semantic.error,
          '--color-error-content': colors.text.night.primary,
        },
      });
    }),
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          light: 'var(--color-primary-light)',
          dark: 'var(--color-primary-dark)',
          content: 'var(--color-primary-content)',
        },
        glow: {
          white: 'var(--color-glow-white)',
          outer: 'var(--color-glow-outer)',
        },
        glass: {
          nav: colors.glass.nav,
          card: colors.glass.card,
          'card-hover': colors.glass.cardHover,
          form: colors.glass.form,
          project: colors.glass.project,
          'project-hover': colors.glass.projectHover,
          border: colors.glass.border,
          'border-hover': colors.glass.borderHover,
          tag: colors.glass.tag,
          'tag-bg': colors.glass.tagBg,
          'tag-bg-hover': colors.glass.tagBgHover,
        },
      },
      fontFamily: {
        ...font.fontFamily,
        sans: [font.fontFamily.primary],
        mono: [font.fontFamily.mono],
      },
      fontWeight: font.fontWeight,
      fontSize: font.fontSize,
      borderRadius: radius,
      boxShadow: shadows,
      dropShadow: dropShadows,
      keyframes: keyframes,
      animation: animations,
    },
  },
  daisyui: {
    themes: [
      "day --default",
      "night --prefersdark",
    ],
    base: true,
    styled: true,
    utils: true,
  },
};